name: Build Cheat

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    name: Build project
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore .

    - name: Build
      run: msbuild -p:Configuration="Release" -p:Platform="x64"

    - name: Install GitHub CLI
      run: choco install gh

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete existing release
      run: |
        $release_id = gh release view x64 --json id --jq ".id" || echo ""
        if ($release_id) {
          gh release delete x64 -y
          gh api -X DELETE /repos/${{ github.repository }}/git/refs/tags/x64
        }

    - name: Release
      id: release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: x64
        release_name: SCS2 Release

    - name: Upload PE
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./x64/Release/scs2.exe
        asset_name: SCS2.exe
        asset_content_type: application/exe